// Mock data for UI development and testing
import type {
  ResearchSession,
  ResearchFinding,
  ResearchSource,
  ResearchPerspective,
  KnowledgeEntity,
  FindingRelationship,
  ResearchContradiction,
  ResearchGap,
  SessionWithDetails,
} from '@/src/types/research';

// Helper to generate IDs
const id = (prefix: string, n: number) => `${prefix}-${n.toString().padStart(3, '0')}`;

// ============================================================
// INVESTIGATION TEMPLATE MOCK DATA
// Theme: Corporate fraud investigation
// ============================================================

export const mockInvestigationSession: ResearchSession = {
  id: 'inv-session-001',
  workspace_id: 'ws-001',
  title: 'TechCorp Financial Irregularities Investigation',
  query: 'Investigate financial irregularities at TechCorp Inc between 2020-2024',
  template_type: 'investigation',
  status: 'completed',
  topic_ids: ['topic-001'],
  parameters: {},
  claim_count: 23,
  source_count: 47,
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-01-15T14:30:00Z',
  completed_at: '2024-01-15T14:30:00Z',
};

export const mockInvestigationFindings: ResearchFinding[] = [
  {
    id: id('find', 1),
    session_id: 'inv-session-001',
    finding_type: 'fact',
    content: 'TechCorp reported $2.3B revenue in Q4 2023, a 45% increase from Q3',
    summary: 'Q4 2023 revenue spike',
    confidence_score: 0.95,
    supporting_sources: [id('src', 1)],
    created_at: '2024-01-15T11:00:00Z',
    temporal_context: 'past',
    event_date: '2023-12-31',
    related_findings: [],
    contradicts: [id('find', 2)],
    is_promoted: true,
  },
  {
    id: id('find', 2),
    session_id: 'inv-session-001',
    finding_type: 'claim',
    content: 'Former employee alleges revenue figures were artificially inflated through shell company transactions',
    summary: 'Whistleblower revenue inflation claim',
    confidence_score: 0.7,
    supporting_sources: [id('src', 2)],
    created_at: '2024-01-15T11:15:00Z',
    temporal_context: 'past',
    date_range_start: '2022-01-01',
    date_range_end: '2023-12-31',
    related_findings: [id('find', 4), id('find', 7)],
    contradicts: [id('find', 1), id('find', 9)],
    is_promoted: true,
  },
  {
    id: id('find', 3),
    session_id: 'inv-session-001',
    finding_type: 'actor',
    content: 'CEO Marcus Chen joined TechCorp in 2019 after leaving Nexus Financial under SEC investigation',
    summary: 'CEO background with SEC history',
    confidence_score: 0.92,
    supporting_sources: [id('src', 3), id('src', 4)],
    created_at: '2024-01-15T11:30:00Z',
    temporal_context: 'historical',
    event_date: '2019-03-15',
    related_findings: [id('find', 6)],
    contradicts: [],
    is_promoted: true,
  },
  {
    id: id('find', 4),
    session_id: 'inv-session-001',
    finding_type: 'relationship',
    content: 'Shell company Apex Holdings shares the same registered address as TechCorp subsidiary in Delaware',
    summary: 'Shell company address link',
    confidence_score: 0.88,
    supporting_sources: [id('src', 5)],
    created_at: '2024-01-15T12:00:00Z',
    temporal_context: 'current',
    related_findings: [id('find', 2), id('find', 7)],
    contradicts: [],
    is_promoted: true,
  },
  {
    id: id('find', 5),
    session_id: 'inv-session-001',
    finding_type: 'event',
    content: 'Board meeting on March 15, 2023 approved $500M stock buyback program despite internal audit concerns',
    summary: 'Stock buyback amid audit concerns',
    confidence_score: 0.85,
    supporting_sources: [id('src', 6)],
    created_at: '2024-01-15T12:30:00Z',
    temporal_context: 'past',
    event_date: '2023-03-15',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
  },
  {
    id: id('find', 6),
    session_id: 'inv-session-001',
    finding_type: 'pattern',
    content: 'Revenue spikes consistently occur in Q4, followed by Q1 restatements, pattern repeated 2020-2023',
    summary: 'Q4 revenue spike pattern',
    confidence_score: 0.9,
    supporting_sources: [id('src', 1), id('src', 7)],
    created_at: '2024-01-15T13:00:00Z',
    temporal_context: 'historical',
    date_range_start: '2020-01-01',
    date_range_end: '2023-12-31',
    related_findings: [id('find', 3), id('find', 10)],
    contradicts: [],
    is_promoted: true,
  },
  {
    id: id('find', 7),
    session_id: 'inv-session-001',
    finding_type: 'evidence',
    content: 'Internal email from CFO Sarah Miller dated Nov 2022: "We need to book the Apex revenue before year-end audit"',
    summary: 'CFO email evidence',
    confidence_score: 0.75,
    supporting_sources: [id('src', 8)],
    created_at: '2024-01-15T13:30:00Z',
    temporal_context: 'past',
    event_date: '2022-11-15',
    related_findings: [id('find', 2), id('find', 4)],
    contradicts: [],
    is_promoted: true,
  },
  {
    id: id('find', 8),
    session_id: 'inv-session-001',
    finding_type: 'gap',
    content: 'No public records found for TechCorp subsidiaries in Cayman Islands despite SEC filing mentions',
    summary: 'Missing Cayman subsidiary records',
    confidence_score: 0.6,
    supporting_sources: [],
    created_at: '2024-01-15T14:00:00Z',
    temporal_context: 'current',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
  },
  {
    id: id('find', 9),
    session_id: 'inv-session-001',
    finding_type: 'claim',
    content: 'TechCorp official statement denies all allegations, attributes revenue growth to "market expansion in Asia"',
    summary: 'Company denial statement',
    confidence_score: 0.95,
    supporting_sources: [id('src', 9)],
    created_at: '2024-01-15T14:15:00Z',
    temporal_context: 'current',
    event_date: '2024-01-14',
    related_findings: [],
    contradicts: [id('find', 2)],
    is_promoted: false,
  },
  {
    id: id('find', 10),
    session_id: 'inv-session-001',
    finding_type: 'fact',
    content: 'SEC opened formal investigation into TechCorp on January 10, 2024',
    summary: 'SEC investigation opened',
    confidence_score: 0.99,
    supporting_sources: [id('src', 10)],
    created_at: '2024-01-15T14:20:00Z',
    temporal_context: 'current',
    event_date: '2024-01-10',
    related_findings: [id('find', 6)],
    contradicts: [],
    is_promoted: true,
  },
];

export const mockInvestigationSources: ResearchSource[] = [
  { id: id('src', 1), session_id: 'inv-session-001', url: 'https://sec.gov/filings/techcorp-10k-2023', url_hash: 'hash1', title: 'TechCorp 10-K Annual Report 2023', domain: 'sec.gov', credibility_score: 0.95, source_type: 'government', content_date: '2024-01-05', discovered_at: '2024-01-15T11:00:00Z', is_global: false, citation_count: 5 },
  { id: id('src', 2), session_id: 'inv-session-001', url: 'https://wsj.com/techcorp-whistleblower', url_hash: 'hash2', title: 'TechCorp Whistleblower Alleges Fraud', domain: 'wsj.com', credibility_score: 0.85, source_type: 'news', content_date: '2024-01-12', discovered_at: '2024-01-15T11:15:00Z', is_global: false, citation_count: 8 },
  { id: id('src', 3), session_id: 'inv-session-001', url: 'https://linkedin.com/in/marcus-chen', url_hash: 'hash3', title: 'Marcus Chen LinkedIn Profile', domain: 'linkedin.com', credibility_score: 0.7, source_type: 'social', discovered_at: '2024-01-15T11:30:00Z', is_global: false, citation_count: 1 },
  { id: id('src', 4), session_id: 'inv-session-001', url: 'https://sec.gov/enforcement/nexus-2018', url_hash: 'hash4', title: 'SEC vs Nexus Financial Settlement 2018', domain: 'sec.gov', credibility_score: 0.98, source_type: 'government', content_date: '2018-06-15', discovered_at: '2024-01-15T11:30:00Z', is_global: false, citation_count: 3 },
  { id: id('src', 5), session_id: 'inv-session-001', url: 'https://opencorporates.com/apex-holdings', url_hash: 'hash5', title: 'Apex Holdings Corporate Registry', domain: 'opencorporates.com', credibility_score: 0.9, source_type: 'corporate', discovered_at: '2024-01-15T12:00:00Z', is_global: false, citation_count: 2 },
  { id: id('src', 6), session_id: 'inv-session-001', url: 'https://techcorp.com/investor/board-minutes', url_hash: 'hash6', title: 'TechCorp Board Meeting Minutes Q1 2023', domain: 'techcorp.com', credibility_score: 0.8, source_type: 'corporate', content_date: '2023-03-20', discovered_at: '2024-01-15T12:30:00Z', is_global: false, citation_count: 1 },
  { id: id('src', 7), session_id: 'inv-session-001', url: 'https://bloomberg.com/techcorp-restatements', url_hash: 'hash7', title: 'TechCorp History of Financial Restatements', domain: 'bloomberg.com', credibility_score: 0.9, source_type: 'news', content_date: '2023-08-10', discovered_at: '2024-01-15T13:00:00Z', is_global: false, citation_count: 4 },
  { id: id('src', 8), session_id: 'inv-session-001', url: 'https://leaked.docs/techcorp-email', url_hash: 'hash8', title: 'Leaked Internal Email (Unverified)', domain: 'leaked.docs', credibility_score: 0.5, source_type: 'unknown', content_date: '2022-11-15', discovered_at: '2024-01-15T13:30:00Z', is_global: false, citation_count: 2 },
  { id: id('src', 9), session_id: 'inv-session-001', url: 'https://techcorp.com/press/response-2024', url_hash: 'hash9', title: 'TechCorp Official Response to Allegations', domain: 'techcorp.com', credibility_score: 0.75, source_type: 'corporate', content_date: '2024-01-14', discovered_at: '2024-01-15T14:15:00Z', is_global: false, citation_count: 3 },
  { id: id('src', 10), session_id: 'inv-session-001', url: 'https://sec.gov/news/techcorp-investigation', url_hash: 'hash10', title: 'SEC Announces TechCorp Investigation', domain: 'sec.gov', credibility_score: 0.99, source_type: 'government', content_date: '2024-01-10', discovered_at: '2024-01-15T14:20:00Z', is_global: false, citation_count: 12 },
];

export const mockInvestigationPerspectives: ResearchPerspective[] = [
  {
    id: id('persp', 1),
    session_id: 'inv-session-001',
    perspective_type: 'financial',
    analysis_text: 'The financial patterns at TechCorp exhibit classic signs of revenue manipulation. The consistent Q4 spikes followed by Q1 restatements suggest channel stuffing or premature revenue recognition. The involvement of shell companies like Apex Holdings indicates potential round-trip transactions designed to inflate top-line growth.',
    key_insights: [
      'Revenue recognition timing appears manipulated',
      'Shell company transactions suggest round-tripping',
      'Stock buyback timing suspicious given internal concerns',
    ],
    recommendations: [
      'Forensic audit of all Apex Holdings transactions',
      'Review all Q4 revenue entries for proper timing',
      'Investigate related-party disclosures',
    ],
    warnings: [
      'Potential securities fraud exposure',
      'Class action lawsuit risk is high',
    ],
    findings_analyzed: [id('find', 1), id('find', 2), id('find', 4), id('find', 6)],
    sources_cited: [id('src', 1), id('src', 5), id('src', 7)],
    created_at: '2024-01-15T14:00:00Z',
  },
  {
    id: id('persp', 2),
    session_id: 'inv-session-001',
    perspective_type: 'journalist',
    analysis_text: 'This story has the hallmarks of a major corporate scandal. The combination of a CEO with prior SEC troubles, whistleblower allegations, and documented patterns creates a compelling narrative. Key sources are credible (SEC filings, WSJ reporting) while some evidence remains unverified (leaked emails).',
    key_insights: [
      'Story has strong documentary evidence',
      'Multiple independent sources corroborate pattern',
      'Company response appears defensive rather than transparent',
    ],
    recommendations: [
      'Seek on-record confirmation of leaked email',
      'Interview former Nexus Financial employees',
      'FOIA request for SEC investigation details',
    ],
    warnings: [
      'Leaked email source credibility uncertain',
      'Company may pursue legal action against publishers',
    ],
    findings_analyzed: [id('find', 2), id('find', 3), id('find', 7), id('find', 9)],
    sources_cited: [id('src', 2), id('src', 4), id('src', 8)],
    created_at: '2024-01-15T14:10:00Z',
  },
  {
    id: id('persp', 3),
    session_id: 'inv-session-001',
    perspective_type: 'network',
    analysis_text: 'Network analysis reveals a tight cluster of connections between TechCorp executives, Apex Holdings, and entities from the Nexus Financial era. Marcus Chen and Sarah Miller both have connections to three of the identified shell companies. The Delaware address sharing pattern suggests coordinated entity creation.',
    key_insights: [
      'CEO and CFO share connections to multiple shell entities',
      'Delaware corporate registry shows clustering pattern',
      'Board members have limited independence from executives',
    ],
    recommendations: [
      'Map full beneficial ownership chain',
      'Investigate board member financial ties',
      'Cross-reference with Panama/Paradise papers data',
    ],
    warnings: [
      'Offshore entities may obscure full network',
      'Some connections may be coincidental',
    ],
    findings_analyzed: [id('find', 3), id('find', 4), id('find', 7)],
    sources_cited: [id('src', 3), id('src', 5)],
    created_at: '2024-01-15T14:20:00Z',
  },
];

export const mockInvestigationEntities: KnowledgeEntity[] = [
  { id: id('ent', 1), canonical_name: 'TechCorp Inc', entity_type: 'organization', aliases: ['TechCorp', 'TC Inc'], name_hash: 'techcorp', description: 'Technology company under SEC investigation for financial irregularities', profile_data: {}, external_ids: {}, mention_count: 15, claim_count: 8, is_verified: false, created_at: '2024-01-15T11:00:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 2), canonical_name: 'Marcus Chen', entity_type: 'person', aliases: ['M. Chen', 'CEO Chen'], name_hash: 'marcus-chen', description: 'CEO of TechCorp, former Nexus Financial executive', profile_data: { title: 'CEO' }, external_ids: {}, mention_count: 8, claim_count: 3, is_verified: false, created_at: '2024-01-15T11:30:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 3), canonical_name: 'Sarah Miller', entity_type: 'person', aliases: ['S. Miller', 'CFO Miller'], name_hash: 'sarah-miller', description: 'CFO of TechCorp, alleged author of leaked email', profile_data: { title: 'CFO' }, external_ids: {}, mention_count: 4, claim_count: 2, is_verified: false, created_at: '2024-01-15T13:30:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 4), canonical_name: 'Apex Holdings LLC', entity_type: 'organization', aliases: ['Apex Holdings', 'Apex'], name_hash: 'apex-holdings', description: 'Shell company sharing address with TechCorp subsidiary', profile_data: { jurisdiction: 'Delaware' }, external_ids: {}, mention_count: 5, claim_count: 2, is_verified: false, created_at: '2024-01-15T12:00:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 5), canonical_name: 'Securities and Exchange Commission', entity_type: 'organization', aliases: ['SEC'], name_hash: 'sec', description: 'US federal regulatory agency investigating TechCorp', profile_data: {}, external_ids: {}, mention_count: 6, claim_count: 3, is_verified: true, created_at: '2024-01-15T11:30:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 6), canonical_name: 'Nexus Financial', entity_type: 'organization', aliases: ['Nexus'], name_hash: 'nexus-financial', description: 'Former employer of Marcus Chen, settled with SEC in 2018', profile_data: {}, external_ids: {}, mention_count: 3, claim_count: 1, is_verified: false, created_at: '2024-01-15T11:30:00Z', updated_at: '2024-01-15T14:30:00Z' },
  { id: id('ent', 7), canonical_name: 'John Davis', entity_type: 'person', aliases: ['J. Davis', 'Whistleblower'], name_hash: 'john-davis', description: 'Former TechCorp employee, whistleblower', profile_data: {}, external_ids: {}, mention_count: 2, claim_count: 1, is_verified: false, created_at: '2024-01-15T11:15:00Z', updated_at: '2024-01-15T14:30:00Z' },
];

export const mockInvestigationRelationships: FindingRelationship[] = [
  { id: id('rel', 1), session_id: 'inv-session-001', source_finding_id: id('find', 2), target_finding_id: id('find', 1), relationship_type: 'contradicts', strength: 0.8, description: 'Whistleblower claim contradicts official revenue figures', created_at: '2024-01-15T13:00:00Z' },
  { id: id('rel', 2), session_id: 'inv-session-001', source_finding_id: id('find', 4), target_finding_id: id('find', 2), relationship_type: 'supports', strength: 0.85, description: 'Shell company address link supports fraud allegation', created_at: '2024-01-15T13:00:00Z' },
  { id: id('rel', 3), session_id: 'inv-session-001', source_finding_id: id('find', 7), target_finding_id: id('find', 4), relationship_type: 'supports', strength: 0.9, description: 'CFO email directly references Apex revenue booking', created_at: '2024-01-15T13:30:00Z' },
  { id: id('rel', 4), session_id: 'inv-session-001', source_finding_id: id('find', 3), target_finding_id: id('find', 6), relationship_type: 'causes', strength: 0.7, description: 'CEO background may explain pattern of financial manipulation', created_at: '2024-01-15T13:00:00Z' },
  { id: id('rel', 5), session_id: 'inv-session-001', source_finding_id: id('find', 6), target_finding_id: id('find', 10), relationship_type: 'causes', strength: 0.95, description: 'Revenue pattern likely triggered SEC investigation', created_at: '2024-01-15T14:20:00Z' },
  { id: id('rel', 6), session_id: 'inv-session-001', source_finding_id: id('find', 9), target_finding_id: id('find', 2), relationship_type: 'contradicts', strength: 0.9, description: 'Company denial contradicts whistleblower allegations', created_at: '2024-01-15T14:15:00Z' },
];

export const mockInvestigationContradictions: ResearchContradiction[] = [
  {
    id: id('contra', 1),
    session_id: 'inv-session-001',
    finding_id_1: id('find', 1),
    finding_id_2: id('find', 2),
    claim_1: 'TechCorp reported $2.3B revenue in Q4 2023',
    claim_2: 'Revenue figures were artificially inflated through shell company transactions',
    source_1: id('src', 1),
    source_2: id('src', 2),
    significance: 'Core allegation of financial fraud',
    resolution_hint: 'Forensic audit required to verify transaction legitimacy',
    created_at: '2024-01-15T13:00:00Z',
  },
  {
    id: id('contra', 2),
    session_id: 'inv-session-001',
    finding_id_1: id('find', 9),
    finding_id_2: id('find', 2),
    claim_1: 'TechCorp denies allegations, attributes growth to Asia expansion',
    claim_2: 'Whistleblower alleges revenue inflation through shell companies',
    source_1: id('src', 9),
    source_2: id('src', 2),
    significance: 'Direct conflict between company statement and whistleblower',
    created_at: '2024-01-15T14:15:00Z',
  },
];

export const mockInvestigationGaps: ResearchGap[] = [
  {
    id: id('gap', 1),
    session_id: 'inv-session-001',
    gap_type: 'evidence',
    description: 'No public records found for TechCorp subsidiaries in Cayman Islands despite SEC filing mentions',
    priority: 'high',
    suggested_queries: ['Cayman Islands corporate registry TechCorp', 'Offshore subsidiaries TechCorp SEC filing'],
    related_finding_ids: [id('find', 8)],
    created_at: '2024-01-15T14:00:00Z',
  },
  {
    id: id('gap', 2),
    session_id: 'inv-session-001',
    gap_type: 'temporal',
    description: 'Limited information about TechCorp activities between 2019-2020 when new management took over',
    priority: 'medium',
    suggested_queries: ['TechCorp 2019 leadership transition', 'Marcus Chen TechCorp appointment'],
    related_finding_ids: [id('find', 3)],
    gap_start: '2019-01-01',
    gap_end: '2020-06-30',
    created_at: '2024-01-15T14:00:00Z',
  },
];

// ============================================================
// FINANCIAL TEMPLATE MOCK DATA
// Theme: AI Startup funding analysis
// ============================================================

export const mockFinancialSession: ResearchSession = {
  id: 'fin-session-001',
  workspace_id: 'ws-001',
  title: 'AI Startup Ecosystem Funding Analysis 2024',
  query: 'Analyze AI startup funding flows and key investors in 2024',
  template_type: 'financial',
  status: 'completed',
  topic_ids: ['topic-002'],
  parameters: {},
  claim_count: 32,
  source_count: 65,
  created_at: '2024-02-01T09:00:00Z',
  updated_at: '2024-02-01T16:00:00Z',
  completed_at: '2024-02-01T16:00:00Z',
};

export const mockFinancialFindings: ResearchFinding[] = [
  {
    id: id('ffind', 1),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'Anthropic raised $4B from Amazon in September 2023, the largest AI funding round of the year',
    summary: 'Anthropic $4B Amazon investment',
    confidence_score: 0.99,
    supporting_sources: [id('fsrc', 1)],
    created_at: '2024-02-01T10:00:00Z',
    temporal_context: 'past',
    event_date: '2023-09-25',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { amount: 4000000000, currency: 'USD', round: 'Series C' },
  },
  {
    id: id('ffind', 2),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'OpenAI valued at $86B following employee share sale in December 2023',
    summary: 'OpenAI $86B valuation',
    confidence_score: 0.95,
    supporting_sources: [id('fsrc', 2)],
    created_at: '2024-02-01T10:15:00Z',
    temporal_context: 'past',
    event_date: '2023-12-20',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { valuation: 86000000000, currency: 'USD' },
  },
  {
    id: id('ffind', 3),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'Sequoia Capital invested in 23 AI startups in 2023, totaling $2.8B in deployed capital',
    summary: 'Sequoia AI investments 2023',
    confidence_score: 0.92,
    supporting_sources: [id('fsrc', 3)],
    created_at: '2024-02-01T10:30:00Z',
    temporal_context: 'past',
    date_range_start: '2023-01-01',
    date_range_end: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { amount: 2800000000, currency: 'USD', deal_count: 23 },
  },
  {
    id: id('ffind', 4),
    session_id: 'fin-session-001',
    finding_type: 'pattern',
    content: 'Enterprise AI startups received 72% of total AI funding in 2023, up from 58% in 2022',
    summary: 'Enterprise AI funding dominance',
    confidence_score: 0.88,
    supporting_sources: [id('fsrc', 4)],
    created_at: '2024-02-01T11:00:00Z',
    temporal_context: 'past',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { enterprise_share_2023: 0.72, enterprise_share_2022: 0.58 },
  },
  {
    id: id('ffind', 5),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'Mistral AI raised $415M Series A at $2B valuation, largest European AI round',
    summary: 'Mistral AI mega Series A',
    confidence_score: 0.95,
    supporting_sources: [id('fsrc', 5)],
    created_at: '2024-02-01T11:30:00Z',
    temporal_context: 'past',
    event_date: '2023-12-11',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { amount: 415000000, valuation: 2000000000, currency: 'USD', round: 'Series A' },
  },
  {
    id: id('ffind', 6),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'Cohere raised $270M Series C led by Inovia Capital at $2.2B valuation',
    summary: 'Cohere Series C',
    confidence_score: 0.93,
    supporting_sources: [id('fsrc', 6)],
    created_at: '2024-02-01T12:00:00Z',
    temporal_context: 'past',
    event_date: '2023-06-08',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
    extracted_data: { amount: 270000000, valuation: 2200000000, currency: 'USD', round: 'Series C' },
  },
  {
    id: id('ffind', 7),
    session_id: 'fin-session-001',
    finding_type: 'claim',
    content: 'Industry analysts predict AI startup funding will exceed $100B globally in 2024',
    summary: '2024 AI funding prediction',
    confidence_score: 0.65,
    supporting_sources: [id('fsrc', 7)],
    created_at: '2024-02-01T12:30:00Z',
    temporal_context: 'prediction',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
    extracted_data: { predicted_amount: 100000000000, currency: 'USD' },
  },
  {
    id: id('ffind', 8),
    session_id: 'fin-session-001',
    finding_type: 'fact',
    content: 'Inflection AI raised $1.3B from Microsoft, Nvidia, Reid Hoffman, Bill Gates',
    summary: 'Inflection AI $1.3B round',
    confidence_score: 0.97,
    supporting_sources: [id('fsrc', 8)],
    created_at: '2024-02-01T13:00:00Z',
    temporal_context: 'past',
    event_date: '2023-06-29',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { amount: 1300000000, currency: 'USD' },
  },
];

export const mockFinancialSources: ResearchSource[] = [
  { id: id('fsrc', 1), session_id: 'fin-session-001', url: 'https://techcrunch.com/anthropic-amazon-4b', url_hash: 'fhash1', title: 'Amazon invests $4B in Anthropic', domain: 'techcrunch.com', credibility_score: 0.9, source_type: 'news', content_date: '2023-09-25', discovered_at: '2024-02-01T10:00:00Z', is_global: false, citation_count: 15 },
  { id: id('fsrc', 2), session_id: 'fin-session-001', url: 'https://bloomberg.com/openai-86b-valuation', url_hash: 'fhash2', title: 'OpenAI valued at $86B in share sale', domain: 'bloomberg.com', credibility_score: 0.92, source_type: 'news', content_date: '2023-12-20', discovered_at: '2024-02-01T10:15:00Z', is_global: false, citation_count: 22 },
  { id: id('fsrc', 3), session_id: 'fin-session-001', url: 'https://pitchbook.com/sequoia-ai-2023', url_hash: 'fhash3', title: 'Sequoia Capital AI Portfolio Analysis', domain: 'pitchbook.com', credibility_score: 0.88, source_type: 'corporate', content_date: '2024-01-15', discovered_at: '2024-02-01T10:30:00Z', is_global: false, citation_count: 8 },
  { id: id('fsrc', 4), session_id: 'fin-session-001', url: 'https://cbinsights.com/ai-funding-2023', url_hash: 'fhash4', title: 'State of AI Funding 2023 Report', domain: 'cbinsights.com', credibility_score: 0.85, source_type: 'corporate', content_date: '2024-01-30', discovered_at: '2024-02-01T11:00:00Z', is_global: false, citation_count: 18 },
  { id: id('fsrc', 5), session_id: 'fin-session-001', url: 'https://ft.com/mistral-ai-funding', url_hash: 'fhash5', title: 'Mistral AI raises record European AI round', domain: 'ft.com', credibility_score: 0.9, source_type: 'news', content_date: '2023-12-11', discovered_at: '2024-02-01T11:30:00Z', is_global: false, citation_count: 12 },
  { id: id('fsrc', 6), session_id: 'fin-session-001', url: 'https://cohere.ai/press/series-c', url_hash: 'fhash6', title: 'Cohere Announces $270M Series C', domain: 'cohere.ai', credibility_score: 0.85, source_type: 'corporate', content_date: '2023-06-08', discovered_at: '2024-02-01T12:00:00Z', is_global: false, citation_count: 6 },
  { id: id('fsrc', 7), session_id: 'fin-session-001', url: 'https://forbes.com/ai-funding-predictions-2024', url_hash: 'fhash7', title: '2024 AI Funding Predictions', domain: 'forbes.com', credibility_score: 0.75, source_type: 'news', content_date: '2024-01-05', discovered_at: '2024-02-01T12:30:00Z', is_global: false, citation_count: 4 },
  { id: id('fsrc', 8), session_id: 'fin-session-001', url: 'https://wsj.com/inflection-ai-funding', url_hash: 'fhash8', title: 'Inflection AI Raises $1.3B from Tech Giants', domain: 'wsj.com', credibility_score: 0.92, source_type: 'news', content_date: '2023-06-29', discovered_at: '2024-02-01T13:00:00Z', is_global: false, citation_count: 14 },
];

export const mockFinancialEntities: KnowledgeEntity[] = [
  { id: id('fent', 1), canonical_name: 'Anthropic', entity_type: 'organization', aliases: ['Anthropic PBC'], name_hash: 'anthropic', description: 'AI safety company, creator of Claude', profile_data: { sector: 'AI', founded: 2021 }, external_ids: {}, mention_count: 5, claim_count: 2, is_verified: true, created_at: '2024-02-01T10:00:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 2), canonical_name: 'OpenAI', entity_type: 'organization', aliases: ['Open AI'], name_hash: 'openai', description: 'AI research company, creator of GPT-4 and ChatGPT', profile_data: { sector: 'AI', founded: 2015 }, external_ids: {}, mention_count: 4, claim_count: 2, is_verified: true, created_at: '2024-02-01T10:15:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 3), canonical_name: 'Sequoia Capital', entity_type: 'organization', aliases: ['Sequoia'], name_hash: 'sequoia', description: 'Venture capital firm, major AI investor', profile_data: { type: 'VC' }, external_ids: {}, mention_count: 3, claim_count: 1, is_verified: true, created_at: '2024-02-01T10:30:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 4), canonical_name: 'Amazon', entity_type: 'organization', aliases: ['Amazon.com', 'AMZN'], name_hash: 'amazon', description: 'Tech giant, Anthropic investor', profile_data: { sector: 'Tech' }, external_ids: { ticker: 'AMZN' }, mention_count: 2, claim_count: 1, is_verified: true, created_at: '2024-02-01T10:00:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 5), canonical_name: 'Mistral AI', entity_type: 'organization', aliases: ['Mistral'], name_hash: 'mistral', description: 'French AI startup, open-weights LLM developer', profile_data: { sector: 'AI', founded: 2023, country: 'France' }, external_ids: {}, mention_count: 2, claim_count: 1, is_verified: false, created_at: '2024-02-01T11:30:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 6), canonical_name: 'Microsoft', entity_type: 'organization', aliases: ['MSFT'], name_hash: 'microsoft', description: 'Tech giant, OpenAI and Inflection investor', profile_data: { sector: 'Tech' }, external_ids: { ticker: 'MSFT' }, mention_count: 3, claim_count: 1, is_verified: true, created_at: '2024-02-01T13:00:00Z', updated_at: '2024-02-01T16:00:00Z' },
  { id: id('fent', 7), canonical_name: 'Nvidia', entity_type: 'organization', aliases: ['NVDA'], name_hash: 'nvidia', description: 'GPU manufacturer, AI infrastructure leader', profile_data: { sector: 'Semiconductors' }, external_ids: { ticker: 'NVDA' }, mention_count: 4, claim_count: 1, is_verified: true, created_at: '2024-02-01T12:00:00Z', updated_at: '2024-02-01T16:00:00Z' },
];

// ============================================================
// MARKET RESEARCH TEMPLATE MOCK DATA
// Theme: Electric vehicle market analysis
// ============================================================

export const mockMarketSession: ResearchSession = {
  id: 'mkt-session-001',
  workspace_id: 'ws-001',
  title: 'Electric Vehicle Market Competitive Analysis 2024',
  query: 'Analyze the competitive landscape of the electric vehicle market in North America',
  template_type: 'market',
  status: 'completed',
  topic_ids: ['topic-003'],
  parameters: {},
  claim_count: 45,
  source_count: 78,
  created_at: '2024-02-15T08:00:00Z',
  updated_at: '2024-02-15T17:00:00Z',
  completed_at: '2024-02-15T17:00:00Z',
};

export const mockMarketFindings: ResearchFinding[] = [
  {
    id: id('mfind', 1),
    session_id: 'mkt-session-001',
    finding_type: 'fact',
    content: 'Tesla sold 1.8 million vehicles globally in 2023, capturing 55% of the US EV market',
    summary: 'Tesla market dominance',
    confidence_score: 0.95,
    supporting_sources: [id('msrc', 1)],
    created_at: '2024-02-15T09:00:00Z',
    temporal_context: 'past',
    date_range_start: '2023-01-01',
    date_range_end: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { market_share: 0.55, units_sold: 1800000 },
  },
  {
    id: id('mfind', 2),
    session_id: 'mkt-session-001',
    finding_type: 'fact',
    content: 'Ford F-150 Lightning became the best-selling electric truck with 24,000 units in Q4 2023',
    summary: 'Ford Lightning truck leadership',
    confidence_score: 0.92,
    supporting_sources: [id('msrc', 2)],
    created_at: '2024-02-15T09:30:00Z',
    temporal_context: 'past',
    event_date: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { units_sold: 24000, segment: 'electric_truck' },
  },
  {
    id: id('mfind', 3),
    session_id: 'mkt-session-001',
    finding_type: 'pattern',
    content: 'Legacy automakers (GM, Ford, VW) collectively increased EV market share from 15% to 28% in 2023',
    summary: 'Legacy automaker EV growth',
    confidence_score: 0.88,
    supporting_sources: [id('msrc', 3)],
    created_at: '2024-02-15T10:00:00Z',
    temporal_context: 'past',
    date_range_start: '2022-01-01',
    date_range_end: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { share_2022: 0.15, share_2023: 0.28 },
  },
  {
    id: id('mfind', 4),
    session_id: 'mkt-session-001',
    finding_type: 'claim',
    content: 'BYD plans to launch 5 EV models in the US market by 2025 at prices 30% below comparable Tesla models',
    summary: 'BYD US market entry plans',
    confidence_score: 0.7,
    supporting_sources: [id('msrc', 4)],
    created_at: '2024-02-15T10:30:00Z',
    temporal_context: 'prediction',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { price_advantage: 0.3, planned_models: 5 },
  },
  {
    id: id('mfind', 5),
    session_id: 'mkt-session-001',
    finding_type: 'fact',
    content: 'Tesla Supercharger network has 50,000+ chargers globally, 5x more than any competitor network',
    summary: 'Tesla charging infrastructure lead',
    confidence_score: 0.95,
    supporting_sources: [id('msrc', 5)],
    created_at: '2024-02-15T11:00:00Z',
    temporal_context: 'current',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { charger_count: 50000 },
  },
  {
    id: id('mfind', 6),
    session_id: 'mkt-session-001',
    finding_type: 'fact',
    content: 'Rivian delivered 50,122 vehicles in 2023, up 174% YoY, but still operating at a loss of $39K per vehicle',
    summary: 'Rivian growth with losses',
    confidence_score: 0.93,
    supporting_sources: [id('msrc', 6)],
    created_at: '2024-02-15T11:30:00Z',
    temporal_context: 'past',
    date_range_start: '2023-01-01',
    date_range_end: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
    extracted_data: { units_delivered: 50122, growth_yoy: 1.74, loss_per_vehicle: -39000 },
  },
  {
    id: id('mfind', 7),
    session_id: 'mkt-session-001',
    finding_type: 'pattern',
    content: 'Average EV transaction price declined 15% in 2023 as competition intensified and Tesla cut prices',
    summary: 'EV price decline trend',
    confidence_score: 0.9,
    supporting_sources: [id('msrc', 7)],
    created_at: '2024-02-15T12:00:00Z',
    temporal_context: 'past',
    date_range_start: '2023-01-01',
    date_range_end: '2023-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: { price_change: -0.15 },
  },
  {
    id: id('mfind', 8),
    session_id: 'mkt-session-001',
    finding_type: 'fact',
    content: 'GM Ultium platform supports 19 different EV models across Chevrolet, Cadillac, GMC, and Buick brands',
    summary: 'GM Ultium platform scale',
    confidence_score: 0.95,
    supporting_sources: [id('msrc', 8)],
    created_at: '2024-02-15T12:30:00Z',
    temporal_context: 'current',
    related_findings: [],
    contradicts: [],
    is_promoted: false,
    extracted_data: { model_count: 19 },
  },
];

export const mockMarketSources: ResearchSource[] = [
  { id: id('msrc', 1), session_id: 'mkt-session-001', url: 'https://insideevs.com/tesla-2023-sales', url_hash: 'mhash1', title: 'Tesla 2023 Global Sales Report', domain: 'insideevs.com', credibility_score: 0.88, source_type: 'news', content_date: '2024-01-02', discovered_at: '2024-02-15T09:00:00Z', is_global: false, citation_count: 10 },
  { id: id('msrc', 2), session_id: 'mkt-session-001', url: 'https://ford.com/press/lightning-q4', url_hash: 'mhash2', title: 'Ford Q4 2023 EV Sales Report', domain: 'ford.com', credibility_score: 0.85, source_type: 'corporate', content_date: '2024-01-08', discovered_at: '2024-02-15T09:30:00Z', is_global: false, citation_count: 6 },
  { id: id('msrc', 3), session_id: 'mkt-session-001', url: 'https://mckinsey.com/ev-market-2023', url_hash: 'mhash3', title: 'EV Market Landscape 2023', domain: 'mckinsey.com', credibility_score: 0.92, source_type: 'corporate', content_date: '2024-02-01', discovered_at: '2024-02-15T10:00:00Z', is_global: false, citation_count: 25 },
  { id: id('msrc', 4), session_id: 'mkt-session-001', url: 'https://reuters.com/byd-us-expansion', url_hash: 'mhash4', title: 'BYD Plans US Market Entry', domain: 'reuters.com', credibility_score: 0.9, source_type: 'news', content_date: '2024-02-10', discovered_at: '2024-02-15T10:30:00Z', is_global: false, citation_count: 15 },
  { id: id('msrc', 5), session_id: 'mkt-session-001', url: 'https://tesla.com/supercharger', url_hash: 'mhash5', title: 'Tesla Supercharger Network Statistics', domain: 'tesla.com', credibility_score: 0.85, source_type: 'corporate', content_date: '2024-01-15', discovered_at: '2024-02-15T11:00:00Z', is_global: false, citation_count: 8 },
  { id: id('msrc', 6), session_id: 'mkt-session-001', url: 'https://sec.gov/rivian-10k-2023', url_hash: 'mhash6', title: 'Rivian 2023 Annual Report', domain: 'sec.gov', credibility_score: 0.98, source_type: 'government', content_date: '2024-02-06', discovered_at: '2024-02-15T11:30:00Z', is_global: false, citation_count: 12 },
  { id: id('msrc', 7), session_id: 'mkt-session-001', url: 'https://jdpower.com/ev-prices-2023', url_hash: 'mhash7', title: 'J.D. Power EV Pricing Study', domain: 'jdpower.com', credibility_score: 0.88, source_type: 'corporate', content_date: '2024-01-20', discovered_at: '2024-02-15T12:00:00Z', is_global: false, citation_count: 9 },
  { id: id('msrc', 8), session_id: 'mkt-session-001', url: 'https://gm.com/ultium-platform', url_hash: 'mhash8', title: 'GM Ultium Platform Overview', domain: 'gm.com', credibility_score: 0.85, source_type: 'corporate', content_date: '2024-01-10', discovered_at: '2024-02-15T12:30:00Z', is_global: false, citation_count: 5 },
];

export const mockMarketPerspectives: ResearchPerspective[] = [
  {
    id: id('mpersp', 1),
    session_id: 'mkt-session-001',
    perspective_type: 'financial',
    analysis_text: 'The EV market is transitioning from growth-at-all-costs to profitability focus. Tesla remains the only consistently profitable pure-play EV maker. Legacy automakers are leveraging existing manufacturing scale to reduce per-unit costs. New entrants like Rivian face significant capital challenges with $39K loss per vehicle.',
    key_insights: [
      'Tesla gross margin remains industry-leading at 18%',
      'Legacy automakers benefit from shared ICE/EV platforms',
      'Rivian and Lucid face existential capital needs',
    ],
    recommendations: [
      'Monitor Tesla margin trajectory as competition intensifies',
      'Assess legacy automaker EV unit economics separately',
      'Track Chinese OEM cost structure for disruption signals',
    ],
    warnings: [
      'Price war eroding industry profitability',
      'High interest rates impacting EV financing demand',
    ],
    findings_analyzed: [id('mfind', 1), id('mfind', 6), id('mfind', 7)],
    sources_cited: [id('msrc', 1), id('msrc', 6), id('msrc', 7)],
    created_at: '2024-02-15T15:00:00Z',
  },
  {
    id: id('mpersp', 2),
    session_id: 'mkt-session-001',
    perspective_type: 'journalist',
    analysis_text: 'The EV narrative is shifting from "Tesla vs. the world" to a multi-polar competitive landscape. Chinese manufacturers represent the biggest disruption threat, while legacy automakers are proving more adaptable than expected. Infrastructure remains the underreported story - charging network access may matter more than vehicle specs.',
    key_insights: [
      'Tesla Supercharger becoming industry standard (NACS)',
      'BYD US entry could reshape market pricing',
      'Consumer range anxiety declining but charging convenience still key',
    ],
    recommendations: [
      'Track NACS adoption across manufacturers',
      'Interview charging network operators for demand trends',
      'Monitor tariff policies affecting Chinese EV imports',
    ],
    warnings: [
      'EV adoption slower than projections in mass market',
      'Political headwinds may affect incentive programs',
    ],
    findings_analyzed: [id('mfind', 4), id('mfind', 5)],
    sources_cited: [id('msrc', 4), id('msrc', 5)],
    created_at: '2024-02-15T15:30:00Z',
  },
];

export const mockMarketEntities: KnowledgeEntity[] = [
  { id: id('ment', 1), canonical_name: 'Tesla Inc', entity_type: 'organization', aliases: ['Tesla', 'TSLA'], name_hash: 'tesla', description: 'Leading EV manufacturer, 55% US market share', profile_data: { sector: 'Automotive', market_share: 0.55 }, external_ids: { ticker: 'TSLA' }, mention_count: 12, claim_count: 5, is_verified: true, created_at: '2024-02-15T09:00:00Z', updated_at: '2024-02-15T17:00:00Z' },
  { id: id('ment', 2), canonical_name: 'Ford Motor Company', entity_type: 'organization', aliases: ['Ford', 'F'], name_hash: 'ford', description: 'Legacy automaker with F-150 Lightning and Mustang Mach-E', profile_data: { sector: 'Automotive' }, external_ids: { ticker: 'F' }, mention_count: 6, claim_count: 2, is_verified: true, created_at: '2024-02-15T09:30:00Z', updated_at: '2024-02-15T17:00:00Z' },
  { id: id('ment', 3), canonical_name: 'General Motors', entity_type: 'organization', aliases: ['GM'], name_hash: 'gm', description: 'Legacy automaker with Ultium platform', profile_data: { sector: 'Automotive' }, external_ids: { ticker: 'GM' }, mention_count: 5, claim_count: 2, is_verified: true, created_at: '2024-02-15T10:00:00Z', updated_at: '2024-02-15T17:00:00Z' },
  { id: id('ment', 4), canonical_name: 'BYD Company', entity_type: 'organization', aliases: ['BYD'], name_hash: 'byd', description: 'Chinese EV manufacturer planning US market entry', profile_data: { sector: 'Automotive', country: 'China' }, external_ids: {}, mention_count: 4, claim_count: 1, is_verified: false, created_at: '2024-02-15T10:30:00Z', updated_at: '2024-02-15T17:00:00Z' },
  { id: id('ment', 5), canonical_name: 'Rivian Automotive', entity_type: 'organization', aliases: ['Rivian', 'RIVN'], name_hash: 'rivian', description: 'EV startup focused on trucks and SUVs', profile_data: { sector: 'Automotive' }, external_ids: { ticker: 'RIVN' }, mention_count: 3, claim_count: 1, is_verified: true, created_at: '2024-02-15T11:30:00Z', updated_at: '2024-02-15T17:00:00Z' },
  { id: id('ment', 6), canonical_name: 'Volkswagen Group', entity_type: 'organization', aliases: ['VW', 'Volkswagen'], name_hash: 'vw', description: 'German automaker with ID series EVs', profile_data: { sector: 'Automotive', country: 'Germany' }, external_ids: {}, mention_count: 2, claim_count: 1, is_verified: true, created_at: '2024-02-15T10:00:00Z', updated_at: '2024-02-15T17:00:00Z' },
];

// ============================================================
// MOCK DATA GETTERS BY TEMPLATE TYPE
// ============================================================

export function getMockSessionData(templateType: 'investigation' | 'financial' | 'market'): SessionWithDetails {
  switch (templateType) {
    case 'investigation':
      return {
        ...mockInvestigationSession,
        findings: mockInvestigationFindings,
        sources: mockInvestigationSources,
        perspectives: mockInvestigationPerspectives,
        relationships: mockInvestigationRelationships,
        contradictions: mockInvestigationContradictions,
        gaps: mockInvestigationGaps,
        causal_chains: [],
      };
    case 'financial':
      return {
        ...mockFinancialSession,
        findings: mockFinancialFindings,
        sources: mockFinancialSources,
        perspectives: [],
        relationships: [],
        contradictions: [],
        gaps: [],
        causal_chains: [],
      };
    case 'market':
      return {
        ...mockMarketSession,
        findings: mockMarketFindings,
        sources: mockMarketSources,
        perspectives: mockMarketPerspectives,
        relationships: [],
        contradictions: [],
        gaps: [],
        causal_chains: [],
      };
  }
}

// Entities are stored separately in knowledge graph, provide helper
export function getMockEntities(templateType: 'investigation' | 'financial' | 'market'): KnowledgeEntity[] {
  switch (templateType) {
    case 'investigation':
      return mockInvestigationEntities;
    case 'financial':
      return mockFinancialEntities;
    case 'market':
      return mockMarketEntities;
  }
}

// Flag to enable/disable mock data
export const USE_MOCK_DATA = true;
