// Mock data for Tech Market Analysis template
import type {
  ResearchSession,
  ResearchFinding,
  ResearchSource,
  ResearchPerspective,
  SessionWithDetails,
} from '@/src/types/research';

import type {
  TechTimelineEvent,
  TechnologyAdoption,
  PredictionMatrixItem,
  TechScenario,
  TechTrend2025,
} from '@/src/types/techMarket';

// Helper to generate IDs
const id = (prefix: string, n: number) => `${prefix}-${n.toString().padStart(3, '0')}`;

// ============================================================
// TECH MARKET TEMPLATE MOCK DATA
// Theme: 2025 Tech Trends and 2026 Predictions
// ============================================================

export const mockTechMarketSession: ResearchSession = {
  id: 'tech-session-001',
  workspace_id: 'ws-001',
  title: 'Software Development Ecosystem 2025-2026 Analysis',
  query: 'Analyze technology trends and predictions for software development, AI/ML, and enterprise stack in 2025-2026',
  template_type: 'tech_market',
  status: 'completed',
  topic_ids: ['topic-tech-001'],
  parameters: {
    focusDomains: ['ai_ml', 'software_development', 'devops_platform', 'enterprise_stack'],
    researchDepth: 'deep',
  },
  claim_count: 35,
  source_count: 52,
  created_at: '2025-12-20T10:00:00Z',
  updated_at: '2025-12-20T16:30:00Z',
  completed_at: '2025-12-20T16:30:00Z',
};

export const mockTechMarketFindings: ResearchFinding[] = [
  // Product Launches
  {
    id: id('tech', 1),
    session_id: 'tech-session-001',
    finding_type: 'event',
    content: 'OpenAI launched GPT-5 in Q3 2025 with 2x performance improvement on reasoning benchmarks, achieving 95% accuracy on complex coding tasks',
    summary: 'GPT-5 launched with major reasoning improvements',
    confidence_score: 0.95,
    supporting_sources: [id('src', 1)],
    created_at: '2025-12-20T11:00:00Z',
    temporal_context: 'past',
    event_date: '2025-09-15',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      product_name: 'GPT-5',
      company: 'OpenAI',
      launch_date: '2025-09-15',
      category: 'LLM',
      key_features: ['2x reasoning improvement', '95% coding accuracy'],
    },
  },
  {
    id: id('tech', 2),
    session_id: 'tech-session-001',
    finding_type: 'event',
    content: 'Anthropic released Claude 4 in Q2 2025 with 200K context window and native tool use capabilities, becoming the leading enterprise AI assistant',
    summary: 'Claude 4 release with 200K context',
    confidence_score: 0.92,
    supporting_sources: [id('src', 2)],
    created_at: '2025-12-20T11:05:00Z',
    temporal_context: 'past',
    event_date: '2025-06-01',
    related_findings: [id('tech', 1)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      product_name: 'Claude 4',
      company: 'Anthropic',
      launch_date: '2025-06-01',
      category: 'LLM',
      key_features: ['200K context', 'Native tool use', 'Enterprise focus'],
    },
  },
  // Funding Rounds
  {
    id: id('tech', 3),
    session_id: 'tech-session-001',
    finding_type: 'evidence',
    content: 'Cursor raised $400M Series B at $4B valuation in Q1 2025, signaling massive VC confidence in AI-native IDE category',
    summary: 'Cursor $400M Series B at $4B valuation',
    confidence_score: 0.88,
    supporting_sources: [id('src', 3)],
    created_at: '2025-12-20T11:10:00Z',
    temporal_context: 'past',
    event_date: '2025-02-15',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      company: 'Cursor',
      amount: 400000000,
      round_type: 'Series B',
      valuation: 4000000000,
      date: '2025-02-15',
    },
  },
  {
    id: id('tech', 4),
    session_id: 'tech-session-001',
    finding_type: 'evidence',
    content: 'Developer tools sector attracted $12B in VC funding in 2025, with AI-native tools capturing 60% of total investment',
    summary: '$12B in developer tools funding, 60% to AI',
    confidence_score: 0.85,
    supporting_sources: [id('src', 4)],
    created_at: '2025-12-20T11:15:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 3)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      metric_name: 'Developer tools VC funding',
      value: 12000000000,
      period: '2025',
      ai_share: 0.6,
    },
  },
  // Adoption Trends
  {
    id: id('tech', 5),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'AI coding assistant adoption reached 65% among professional developers in 2025, up from 35% in 2024, with GitHub Copilot leading at 45% market share',
    summary: '65% developer AI assistant adoption in 2025',
    confidence_score: 0.90,
    supporting_sources: [id('src', 5)],
    created_at: '2025-12-20T11:20:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 1), id('tech', 2)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      technology: 'AI coding assistants',
      adoption_rate: 65,
      growth_from_2024: 30,
      market_leader: 'GitHub Copilot',
      leader_share: 45,
    },
  },
  {
    id: id('tech', 6),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Kubernetes adoption in enterprises stabilized at 78% in 2025, with focus shifting to platform engineering and developer experience improvements',
    summary: 'Kubernetes at 78% enterprise adoption',
    confidence_score: 0.87,
    supporting_sources: [id('src', 6)],
    created_at: '2025-12-20T11:25:00Z',
    temporal_context: 'present',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      technology: 'Kubernetes',
      adoption_rate: 78,
      segment: 'enterprise',
      trend: 'stable',
    },
  },
  // 2026 Predictions
  {
    id: id('tech', 7),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'AI-generated code expected to reach 80% of new code by end of 2026, with human developers shifting to review, architecture, and prompt engineering roles',
    summary: '80% AI-generated code prediction for 2026',
    confidence_score: 0.72,
    supporting_sources: [id('src', 7)],
    created_at: '2025-12-20T11:30:00Z',
    temporal_context: 'predicted',
    event_date: '2026-12-31',
    related_findings: [id('tech', 5)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'AI-generated code reaches 80% of new code',
      timeframe: 'Q4_2026',
      confidence: 0.72,
      source_type: 'analyst_report',
      prediction_basis: ['2025 adoption at 65%', 'Rapid AI improvement trajectory'],
      risk_factors: ['Enterprise security concerns', 'Code quality debates'],
    },
  },
  {
    id: id('tech', 8),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Platform engineering will become standard practice in 80% of large enterprises by Q3 2026, driven by developer productivity demands',
    summary: 'Platform engineering standard in 80% of enterprises by 2026',
    confidence_score: 0.78,
    supporting_sources: [id('src', 8)],
    created_at: '2025-12-20T11:35:00Z',
    temporal_context: 'predicted',
    event_date: '2026-09-30',
    related_findings: [id('tech', 6)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'Platform engineering becomes enterprise standard',
      timeframe: 'Q3_2026',
      confidence: 0.78,
      source_type: 'industry_survey',
    },
  },
  {
    id: id('tech', 9),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Vector databases market projected to reach $8B by 2026, with Pinecone and Weaviate emerging as category leaders for RAG applications',
    summary: 'Vector DB market to hit $8B in 2026',
    confidence_score: 0.75,
    supporting_sources: [id('src', 9)],
    created_at: '2025-12-20T11:40:00Z',
    temporal_context: 'predicted',
    event_date: '2026-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'Vector database market reaches $8B',
      timeframe: 'Q4_2026',
      confidence: 0.75,
      market_leaders: ['Pinecone', 'Weaviate'],
    },
  },
  {
    id: id('tech', 10),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Rust adoption in systems programming expected to double in 2026, driven by memory safety requirements and AWS/Microsoft infrastructure investment',
    summary: 'Rust adoption to double in 2026',
    confidence_score: 0.70,
    supporting_sources: [id('src', 10)],
    created_at: '2025-12-20T11:45:00Z',
    temporal_context: 'predicted',
    event_date: '2026-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'Rust adoption doubles',
      timeframe: 'Q4_2026',
      technology: 'Rust',
      drivers: ['Memory safety', 'AWS investment', 'Microsoft investment'],
    },
  },
  // Developer Sentiment
  {
    id: id('tech', 11),
    session_id: 'tech-session-001',
    finding_type: 'claim',
    content: 'Stack Overflow 2025 Survey: 72% of developers report productivity gains from AI tools, but 45% express concerns about code quality and technical debt',
    summary: '72% report AI productivity gains, 45% quality concerns',
    confidence_score: 0.92,
    supporting_sources: [id('src', 11)],
    created_at: '2025-12-20T11:50:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 5)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      topic: 'AI coding tools',
      sentiment: 'mixed',
      sample_size: 65000,
      source: 'Stack Overflow Developer Survey 2025',
      productivity_positive: 72,
      quality_concerns: 45,
    },
  },
  // Market Metrics
  {
    id: id('tech', 12),
    session_id: 'tech-session-001',
    finding_type: 'fact',
    content: 'Global cloud infrastructure market reached $250B in 2025, with AWS maintaining 32% share, Azure at 24%, and GCP at 12%',
    summary: 'Cloud market at $250B, AWS leads at 32%',
    confidence_score: 0.94,
    supporting_sources: [id('src', 12)],
    created_at: '2025-12-20T11:55:00Z',
    temporal_context: 'present',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      metric_name: 'Cloud infrastructure market size',
      value: 250000000000,
      period: '2025',
      shares: { AWS: 32, Azure: 24, GCP: 12 },
    },
  },
  // Acquisitions
  {
    id: id('tech', 13),
    session_id: 'tech-session-001',
    finding_type: 'event',
    content: 'Microsoft acquired AI code review startup CodeReview.ai for $1.2B in Q2 2025, integrating with GitHub and Azure DevOps',
    summary: 'Microsoft acquires CodeReview.ai for $1.2B',
    confidence_score: 0.88,
    supporting_sources: [id('src', 13)],
    created_at: '2025-12-20T12:00:00Z',
    temporal_context: 'past',
    event_date: '2025-05-20',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      acquirer: 'Microsoft',
      target: 'CodeReview.ai',
      amount: 1200000000,
      date: '2025-05-20',
      strategic_rationale: 'GitHub integration, DevOps enhancement',
    },
  },
  // Open Source Events
  {
    id: id('tech', 14),
    session_id: 'tech-session-001',
    finding_type: 'event',
    content: 'Next.js 15 released with React Server Components by default and built-in Turbopack, achieving 10x faster cold starts',
    summary: 'Next.js 15 with RSC default and Turbopack',
    confidence_score: 0.95,
    supporting_sources: [id('src', 14)],
    created_at: '2025-12-20T12:05:00Z',
    temporal_context: 'past',
    event_date: '2025-10-01',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      project: 'Next.js',
      event_type: 'major_release',
      version: '15.0',
      key_features: ['RSC default', 'Turbopack', '10x faster cold starts'],
    },
  },
  // Gaps
  {
    id: id('tech', 15),
    session_id: 'tech-session-001',
    finding_type: 'gap',
    content: 'Limited data on AI coding tool impact on junior developer learning and skill development over time',
    summary: 'Gap: AI impact on junior developer learning',
    confidence_score: 0.60,
    supporting_sources: [],
    created_at: '2025-12-20T12:10:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 5), id('tech', 7)],
    contradicts: [],
    is_promoted: false,
    extracted_data: {
      topic: 'AI impact on developer education',
      importance: 'high',
      suggested_research: 'Longitudinal studies on junior developer skill development with AI tools',
    },
  },
  // More predictions for scenarios
  {
    id: id('tech', 16),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'AI agents expected to handle 40% of routine DevOps tasks by Q2 2026, including incident response, deployment, and infrastructure scaling',
    summary: 'AI agents to handle 40% of DevOps tasks by Q2 2026',
    confidence_score: 0.68,
    supporting_sources: [id('src', 15)],
    created_at: '2025-12-20T12:15:00Z',
    temporal_context: 'predicted',
    event_date: '2026-06-30',
    related_findings: [id('tech', 8)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'AI agents handle 40% of DevOps tasks',
      timeframe: 'Q2_2026',
      confidence: 0.68,
    },
  },
  {
    id: id('tech', 17),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Edge AI inference expected to grow 5x by end of 2026, driven by privacy requirements and latency-sensitive applications',
    summary: 'Edge AI to grow 5x by 2026',
    confidence_score: 0.65,
    supporting_sources: [id('src', 16)],
    created_at: '2025-12-20T12:20:00Z',
    temporal_context: 'predicted',
    event_date: '2026-12-31',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      prediction: 'Edge AI inference grows 5x',
      timeframe: 'Q4_2026',
      drivers: ['Privacy requirements', 'Latency sensitivity'],
    },
  },
  // Risk patterns
  {
    id: id('tech', 18),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Cloud cost overruns remain a critical challenge, with 68% of enterprises exceeding AI/ML infrastructure budgets by 40% or more in 2025',
    summary: '68% enterprises exceed AI infra budgets by 40%+',
    confidence_score: 0.85,
    supporting_sources: [id('src', 17)],
    created_at: '2025-12-20T12:25:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 12)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      topic: 'Cloud cost management',
      risk_level: 'high',
      affected_enterprises: 68,
      budget_overrun: 40,
    },
  },
  // Opportunity patterns
  {
    id: id('tech', 19),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Growing demand for AI-native security tools presents $15B market opportunity by 2026, with current market largely underserved',
    summary: 'AI security tools: $15B opportunity by 2026',
    confidence_score: 0.72,
    supporting_sources: [id('src', 18)],
    created_at: '2025-12-20T12:30:00Z',
    temporal_context: 'present',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      opportunity: 'AI-native security tools',
      market_size: 15000000000,
      timeframe: '2026',
      current_state: 'underserved',
    },
  },
  {
    id: id('tech', 20),
    session_id: 'tech-session-001',
    finding_type: 'pattern',
    content: 'Developer experience (DX) platforms showing 3x growth, with companies prioritizing internal tooling to compete for developer talent',
    summary: 'DX platforms growing 3x, driven by talent competition',
    confidence_score: 0.80,
    supporting_sources: [id('src', 19)],
    created_at: '2025-12-20T12:35:00Z',
    temporal_context: 'present',
    related_findings: [id('tech', 8)],
    contradicts: [],
    is_promoted: true,
    extracted_data: {
      trend: 'Developer experience platforms',
      growth_rate: 3,
      driver: 'Developer talent competition',
    },
  },
];

export const mockTechMarketSources: ResearchSource[] = [
  {
    id: id('src', 1),
    session_id: 'tech-session-001',
    is_global: false,
    url: 'https://openai.com/blog/gpt-5',
    url_hash: 'openai-gpt5',
    title: 'Introducing GPT-5: A New Era in AI Reasoning',
    domain: 'openai.com',
    snippet: 'Today we release GPT-5, our most capable model yet...',
    credibility_score: 0.95,
    source_type: 'corporate',
    discovered_at: '2025-12-20T11:00:00Z',
    citation_count: 1,
  },
  {
    id: id('src', 2),
    session_id: 'tech-session-001',
    is_global: false,
    url: 'https://anthropic.com/news/claude-4',
    url_hash: 'anthropic-claude4',
    title: 'Claude 4: Extended Context and Native Tools',
    domain: 'anthropic.com',
    snippet: 'Claude 4 brings 200K context and native tool use...',
    credibility_score: 0.94,
    source_type: 'corporate',
    discovered_at: '2025-12-20T11:05:00Z',
    citation_count: 1,
  },
  {
    id: id('src', 3),
    session_id: 'tech-session-001',
    is_global: false,
    url: 'https://techcrunch.com/2025/02/cursor-series-b',
    url_hash: 'tc-cursor',
    title: 'Cursor raises $400M at $4B valuation for AI-native IDE',
    domain: 'techcrunch.com',
    snippet: 'Cursor, the AI-first code editor, announced a $400M Series B...',
    credibility_score: 0.88,
    source_type: 'news',
    discovered_at: '2025-12-20T11:10:00Z',
    citation_count: 1,
  },
  {
    id: id('src', 4),
    session_id: 'tech-session-001',
    is_global: false,
    url: 'https://venturebeat.com/2025/12/devtools-funding-report',
    url_hash: 'vb-devtools',
    title: '2025 Developer Tools Funding Report',
    domain: 'venturebeat.com',
    snippet: 'Developer tools sector attracted $12B in VC funding...',
    credibility_score: 0.85,
    source_type: 'news',
    discovered_at: '2025-12-20T11:15:00Z',
    citation_count: 1,
  },
  {
    id: id('src', 5),
    session_id: 'tech-session-001',
    is_global: false,
    url: 'https://insights.stackoverflow.com/survey/2025',
    url_hash: 'so-survey-2025',
    title: 'Stack Overflow Developer Survey 2025',
    domain: 'stackoverflow.com',
    snippet: 'Our annual survey of 65,000+ developers reveals...',
    credibility_score: 0.92,
    source_type: 'news',
    discovered_at: '2025-12-20T11:20:00Z',
    citation_count: 2,
  },
];

export const mockTechMarketPerspectives: ResearchPerspective[] = [
  {
    id: id('persp', 1),
    session_id: 'tech-session-001',
    perspective_type: 'technological',
    analysis_text: `The technology landscape in 2025 has been fundamentally reshaped by AI integration. AI coding assistants have crossed the mainstream adoption threshold, with 65% of professional developers now using them daily. This represents a paradigm shift in how software is created.

Looking ahead to 2026, we anticipate AI-generated code reaching 80% of new code production. This will transform developer roles from writing code to reviewing, architecting, and prompt engineering. Companies that fail to adopt AI-native development workflows risk falling behind in productivity.

The platform engineering movement is accelerating, with internal developer platforms becoming essential for enterprise competitiveness. Combined with AI agents handling routine DevOps tasks, we expect significant improvements in developer velocity.`,
    key_insights: [
      'AI coding assistants reached mainstream adoption at 65%',
      'Developer roles shifting to review and architecture',
      'Platform engineering becoming enterprise standard',
      'AI agents to handle 40% of DevOps tasks by Q2 2026',
      'Edge AI growing 5x driven by privacy requirements',
    ],
    recommendations: [
      'Invest in AI-native development workflows immediately',
      'Build internal developer platforms to improve DX',
      'Prepare for developer role evolution with training programs',
      'Evaluate edge AI for latency-sensitive applications',
    ],
    warnings: [
      'Cloud cost overruns affecting 68% of enterprises',
      'Junior developer skill development concerns with AI reliance',
      'Code quality debates may slow enterprise adoption',
    ],
    confidence: 0.85,
    findings_analyzed: [id('tech', 1), id('tech', 5), id('tech', 7), id('tech', 8)],
    sources_cited: [id('src', 1), id('src', 5)],
    created_at: '2025-12-20T14:00:00Z',
  },
  {
    id: id('persp', 2),
    session_id: 'tech-session-001',
    perspective_type: 'financial',
    analysis_text: `The developer tools market has attracted unprecedented investment in 2025, with $12B in VC funding and 60% flowing to AI-native tools. Cursor's $4B valuation at Series B signals massive confidence in the AI IDE category.

The cloud infrastructure market reached $250B with continued AWS dominance at 32%. However, cloud cost overruns remain a critical challenge, with enterprises exceeding AI/ML budgets by 40% or more.

Key investment opportunities for 2026 include AI security tools ($15B market opportunity), vector databases ($8B projected), and developer experience platforms (3x growth trajectory).`,
    key_insights: [
      '$12B in dev tools funding, 60% to AI-native tools',
      'Cursor valued at $4B signals AI IDE opportunity',
      'Cloud market at $250B with AWS leading at 32%',
      'AI security tools present $15B opportunity',
      'Vector databases projected at $8B by 2026',
    ],
    recommendations: [
      'Prioritize AI-native development tool investments',
      'Implement FinOps practices for AI workloads',
      'Explore AI security tool market entry',
      'Consider vector database infrastructure plays',
    ],
    warnings: [
      '68% of enterprises exceeding AI infrastructure budgets',
      'Market consolidation may limit exit opportunities',
      'Economic headwinds could slow enterprise adoption',
    ],
    confidence: 0.82,
    findings_analyzed: [id('tech', 3), id('tech', 4), id('tech', 12), id('tech', 18)],
    sources_cited: [id('src', 3), id('src', 4)],
    created_at: '2025-12-20T14:30:00Z',
  },
];

// Pre-structured data for dashboard components
export const mockTimelineEvents: TechTimelineEvent[] = [
  {
    id: 'tle-001',
    quarter: 'Q1',
    year: 2025,
    title: 'Cursor $400M Series B',
    description: 'AI-native IDE raises massive funding round at $4B valuation',
    domain: 'software_development',
    isPrediction: false,
    confidenceScore: 0.88,
    confidenceRange: { low: 0.80, high: 0.95 },
    impact: 'high',
    relatedTechnologies: ['Cursor', 'AI', 'IDE'],
  },
  {
    id: 'tle-002',
    quarter: 'Q2',
    year: 2025,
    title: 'Claude 4 Release',
    description: '200K context window and native tool use capabilities',
    domain: 'ai_ml',
    isPrediction: false,
    confidenceScore: 0.92,
    confidenceRange: { low: 0.85, high: 0.98 },
    impact: 'high',
    relatedTechnologies: ['Claude', 'Anthropic', 'LLM'],
  },
  {
    id: 'tle-003',
    quarter: 'Q3',
    year: 2025,
    title: 'GPT-5 Launch',
    description: '2x reasoning improvement and 95% coding accuracy',
    domain: 'ai_ml',
    isPrediction: false,
    confidenceScore: 0.95,
    confidenceRange: { low: 0.90, high: 1.0 },
    impact: 'high',
    relatedTechnologies: ['GPT', 'OpenAI', 'LLM'],
  },
  {
    id: 'tle-004',
    quarter: 'Q4',
    year: 2025,
    title: 'Next.js 15 Release',
    description: 'RSC by default, Turbopack, 10x faster cold starts',
    domain: 'software_development',
    isPrediction: false,
    confidenceScore: 0.95,
    confidenceRange: { low: 0.90, high: 1.0 },
    impact: 'medium',
    relatedTechnologies: ['Next.js', 'React', 'Vercel'],
  },
  {
    id: 'tle-005',
    quarter: 'Q2',
    year: 2026,
    title: 'AI Agents Handle 40% of DevOps',
    description: 'AI agents automate incident response, deployment, and scaling',
    domain: 'devops_platform',
    isPrediction: true,
    confidenceScore: 0.68,
    confidenceRange: { low: 0.55, high: 0.80 },
    impact: 'high',
    relatedTechnologies: ['AI Agents', 'DevOps', 'Automation'],
  },
  {
    id: 'tle-006',
    quarter: 'Q3',
    year: 2026,
    title: 'Platform Engineering Standard',
    description: '80% of large enterprises adopt platform engineering',
    domain: 'devops_platform',
    isPrediction: true,
    confidenceScore: 0.78,
    confidenceRange: { low: 0.65, high: 0.88 },
    impact: 'high',
    relatedTechnologies: ['IDP', 'Platform Engineering', 'DevEx'],
  },
  {
    id: 'tle-007',
    quarter: 'Q4',
    year: 2026,
    title: '80% AI-Generated Code',
    description: 'AI generates majority of new code, developer roles shift',
    domain: 'software_development',
    isPrediction: true,
    confidenceScore: 0.72,
    confidenceRange: { low: 0.58, high: 0.85 },
    impact: 'high',
    relatedTechnologies: ['AI Coding', 'GitHub Copilot', 'Cursor'],
  },
  {
    id: 'tle-008',
    quarter: 'Q4',
    year: 2026,
    title: 'Vector DB Market $8B',
    description: 'Vector databases reach $8B market size',
    domain: 'data_analytics',
    isPrediction: true,
    confidenceScore: 0.75,
    confidenceRange: { low: 0.62, high: 0.87 },
    impact: 'medium',
    relatedTechnologies: ['Pinecone', 'Weaviate', 'RAG'],
  },
];

export const mockAdoptionCurves: TechnologyAdoption[] = [
  {
    id: 'adopt-001',
    name: 'AI Coding Assistants',
    domain: 'software_development',
    currentPhase: 'early_majority',
    adoptionPercentage: 65,
    curveData: [],
    projectedPeakYear: 2027,
    marketSize: '$12B',
    keyDrivers: ['Productivity gains', 'GitHub Copilot success', 'Enterprise adoption'],
    barriers: ['Code quality concerns', 'Security audit requirements'],
  },
  {
    id: 'adopt-002',
    name: 'Kubernetes',
    domain: 'devops_platform',
    currentPhase: 'late_majority',
    adoptionPercentage: 78,
    curveData: [],
    projectedPeakYear: 2025,
    marketSize: '$8B',
    keyDrivers: ['Container orchestration standard', 'Cloud-native movement'],
    barriers: ['Complexity', 'Operational overhead'],
  },
  {
    id: 'adopt-003',
    name: 'Vector Databases',
    domain: 'data_analytics',
    currentPhase: 'early_adopters',
    adoptionPercentage: 15,
    curveData: [],
    projectedPeakYear: 2028,
    marketSize: '$8B (projected 2026)',
    keyDrivers: ['RAG applications', 'Semantic search', 'AI infrastructure'],
    barriers: ['New technology learning curve', 'Integration complexity'],
  },
  {
    id: 'adopt-004',
    name: 'Rust',
    domain: 'software_development',
    currentPhase: 'early_adopters',
    adoptionPercentage: 12,
    curveData: [],
    projectedPeakYear: 2029,
    marketSize: 'Growing',
    keyDrivers: ['Memory safety', 'AWS investment', 'Microsoft adoption'],
    barriers: ['Learning curve', 'Ecosystem maturity'],
  },
];

export const mockMatrixItems: PredictionMatrixItem[] = [
  {
    id: 'matrix-001',
    title: 'AI Coding Dominance',
    description: 'AI-generated code reaching 80% of new development',
    domain: 'software_development',
    type: 'opportunity',
    impact: 85,
    probability: 72,
    quadrant: 'act_now',
    timeframe: '12-18 months',
    captureActions: ['Invest in AI coding tools', 'Train developers on prompt engineering'],
  },
  {
    id: 'matrix-002',
    title: 'Cloud Cost Spiral',
    description: 'AI workload costs exceeding budgets by 40%+',
    domain: 'cloud_infrastructure',
    type: 'risk',
    impact: 75,
    probability: 68,
    quadrant: 'act_now',
    timeframe: '6-12 months',
    mitigationActions: ['Implement FinOps', 'Optimize AI workloads', 'Consider reserved capacity'],
  },
  {
    id: 'matrix-003',
    title: 'AI Security Tools Gap',
    description: '$15B market opportunity in AI-native security',
    domain: 'security',
    type: 'opportunity',
    impact: 80,
    probability: 65,
    quadrant: 'act_now',
    timeframe: '12-24 months',
    captureActions: ['Evaluate AI security vendors', 'Build internal capabilities'],
  },
  {
    id: 'matrix-004',
    title: 'Junior Developer Skills Gap',
    description: 'AI reliance impacting fundamental skill development',
    domain: 'software_development',
    type: 'risk',
    impact: 60,
    probability: 55,
    quadrant: 'monitor',
    timeframe: '24-36 months',
    mitigationActions: ['Balanced training programs', 'Code review requirements'],
  },
  {
    id: 'matrix-005',
    title: 'Platform Engineering Wave',
    description: '80% enterprise adoption by Q3 2026',
    domain: 'devops_platform',
    type: 'opportunity',
    impact: 70,
    probability: 78,
    quadrant: 'act_now',
    timeframe: '12-18 months',
    captureActions: ['Start IDP initiative', 'Hire platform engineers'],
  },
];

export const mockScenarios: TechScenario[] = [
  {
    id: 'scenario-001',
    predictionId: 'tech-007',
    predictionTitle: 'AI-Generated Code Reaches 80%',
    domain: 'software_development',
    scenarios: {
      bull: {
        probability: 25,
        outcome: '90%+ AI-generated code by Q3 2026, developer roles fully transformed',
        keyAssumptions: ['GPT-5 exceeds expectations', 'Enterprise adoption accelerates', 'Regulatory clarity'],
        implications: ['Massive productivity gains', 'Developer role revolution', 'New skill requirements'],
        timeframe: 'Q3 2026',
      },
      base: {
        probability: 50,
        outcome: '75-80% AI-assisted code by Q4 2026, gradual role evolution',
        keyAssumptions: ['Steady AI improvement', 'Mixed enterprise adoption', 'Quality concerns addressed'],
        implications: ['Significant productivity gains', 'Gradual workflow changes', 'Training needed'],
        timeframe: 'Q4 2026',
      },
      bear: {
        probability: 25,
        outcome: '50-60% AI-assisted code, slower transformation',
        keyAssumptions: ['Technical barriers', 'Regulatory friction', 'Security incidents'],
        implications: ['Moderate changes', 'Traditional development persists', 'Delayed ROI'],
        timeframe: 'Q1 2027',
      },
    },
  },
  {
    id: 'scenario-002',
    predictionId: 'tech-008',
    predictionTitle: 'Platform Engineering Becomes Standard',
    domain: 'devops_platform',
    scenarios: {
      bull: {
        probability: 30,
        outcome: '90% adoption by Q2 2026, fully automated golden paths',
        keyAssumptions: ['Strong tooling maturity', 'Clear ROI demonstrated', 'Talent availability'],
        implications: ['10x developer velocity', 'Reduced ops burden', 'Platform teams scale'],
        timeframe: 'Q2 2026',
      },
      base: {
        probability: 50,
        outcome: '80% adoption by Q3 2026, mature IDP implementations',
        keyAssumptions: ['Normal adoption curve', 'Continued investment', 'Skills development'],
        implications: ['3-5x velocity improvement', 'Standardized workflows', 'Cultural shift'],
        timeframe: 'Q3 2026',
      },
      bear: {
        probability: 20,
        outcome: '60% adoption by Q4 2026, fragmented implementations',
        keyAssumptions: ['Complexity challenges', 'Budget constraints', 'Talent shortage'],
        implications: ['Inconsistent results', 'Slower transformation', 'Vendor dependency'],
        timeframe: 'Q4 2026',
      },
    },
  },
];

export const mockTrends2025: TechTrend2025[] = [
  {
    id: 'trend-001',
    name: 'AI-Native Development',
    domain: 'software_development',
    direction: 'accelerating',
    momentum: 92,
    description: 'AI coding assistants and AI-first IDEs reshaping development workflows',
    keyPlayers: ['GitHub Copilot', 'Cursor', 'Claude'],
    enterpriseRelevance: 'high',
    signals: ['65% adoption rate', '$12B funding', 'Productivity data'],
  },
  {
    id: 'trend-002',
    name: 'Platform Engineering',
    domain: 'devops_platform',
    direction: 'accelerating',
    momentum: 85,
    description: 'Internal developer platforms becoming enterprise standard',
    keyPlayers: ['Backstage', 'Port', 'Humanitec'],
    enterpriseRelevance: 'high',
    signals: ['3x growth', 'Gartner hype cycle', 'Enterprise adoption'],
  },
  {
    id: 'trend-003',
    name: 'Vector Databases',
    domain: 'data_analytics',
    direction: 'accelerating',
    momentum: 78,
    description: 'Vector DBs essential for RAG and semantic search applications',
    keyPlayers: ['Pinecone', 'Weaviate', 'Chroma'],
    enterpriseRelevance: 'high',
    signals: ['$8B projection', 'RAG adoption', 'LLM integration'],
  },
  {
    id: 'trend-004',
    name: 'Rust Adoption',
    domain: 'software_development',
    direction: 'accelerating',
    momentum: 65,
    description: 'Systems programming shifting to Rust for memory safety',
    keyPlayers: ['AWS', 'Microsoft', 'Google'],
    enterpriseRelevance: 'medium',
    signals: ['AWS investment', 'Linux kernel adoption', 'Security requirements'],
  },
  {
    id: 'trend-005',
    name: 'FinOps Maturity',
    domain: 'cloud_infrastructure',
    direction: 'accelerating',
    momentum: 72,
    description: 'Cloud cost optimization becoming critical capability',
    keyPlayers: ['Kubecost', 'CloudHealth', 'Spot'],
    enterpriseRelevance: 'high',
    signals: ['68% budget overruns', 'AI cost explosion', 'CFO pressure'],
  },
  {
    id: 'trend-006',
    name: 'AI Agents',
    domain: 'ai_ml',
    direction: 'accelerating',
    momentum: 82,
    description: 'Autonomous AI agents for development and operations tasks',
    keyPlayers: ['OpenAI', 'Anthropic', 'Devin'],
    enterpriseRelevance: 'high',
    signals: ['40% DevOps automation projection', 'Agentic frameworks', 'Tool use'],
  },
];

// Session with all details
export const mockTechMarketSessionWithDetails: SessionWithDetails = {
  ...mockTechMarketSession,
  findings: mockTechMarketFindings,
  sources: mockTechMarketSources,
  perspectives: mockTechMarketPerspectives,
  relationships: [],
  contradictions: [],
  gaps: [
    {
      id: 'gap-001',
      session_id: 'tech-session-001',
      gap_type: 'topic',
      description: 'AI impact on junior developer learning and skill development',
      priority: 'high',
      suggested_queries: ['AI coding assistant impact on developer education'],
      related_finding_ids: [id('tech', 5), id('tech', 7)],
      created_at: '2025-12-20T12:10:00Z',
    },
  ],
  causal_chains: [],
};
