/**
 * Mock data for visual regression testing of View components.
 * Provides realistic sample data for all view types.
 */

import type {
  SessionWithDetails,
  ResearchFinding,
  ResearchSource,
  ResearchContradiction,
  ResearchGap,
  CausalChain,
  KnowledgeEntity,
  ResearchPerspective,
} from '@/src/types/research';

// Mock findings
export const mockFindings: ResearchFinding[] = [
  {
    id: 'finding-1',
    session_id: 'session-1',
    finding_type: 'fact',
    content: 'The company reported a 25% increase in quarterly revenue, driven primarily by strong performance in the cloud services division.',
    confidence_score: 0.92,
    supporting_sources: ['source-1', 'source-2'],
    temporal_context: 'current',
    event_date: '2024-01-15',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'finding-2',
    session_id: 'session-1',
    finding_type: 'claim',
    content: 'Industry analysts predict continued growth in the sector, with an estimated market size of $50 billion by 2025.',
    confidence_score: 0.75,
    supporting_sources: ['source-3'],
    temporal_context: 'prediction',
    related_findings: ['finding-1'],
    contradicts: [],
    is_promoted: false,
    created_at: '2024-01-20T10:05:00Z',
  },
  {
    id: 'finding-3',
    session_id: 'session-1',
    finding_type: 'event',
    content: 'The CEO announced a major restructuring initiative during the annual shareholder meeting.',
    confidence_score: 0.88,
    supporting_sources: ['source-1', 'source-4'],
    temporal_context: 'current',
    event_date: '2024-01-10',
    related_findings: [],
    contradicts: [],
    is_promoted: true,
    created_at: '2024-01-20T10:10:00Z',
  },
  {
    id: 'finding-4',
    session_id: 'session-1',
    finding_type: 'pattern',
    content: 'Historical data shows consistent seasonal fluctuations in sales during Q4, with peaks around holiday periods.',
    confidence_score: 0.65,
    supporting_sources: ['source-2'],
    temporal_context: 'historical',
    related_findings: ['finding-1'],
    contradicts: [],
    is_promoted: false,
    created_at: '2024-01-20T10:15:00Z',
  },
  {
    id: 'finding-5',
    session_id: 'session-1',
    finding_type: 'relationship',
    content: 'The partnership with TechCorp has accelerated product development timelines by approximately 40%.',
    confidence_score: 0.82,
    supporting_sources: ['source-3', 'source-4'],
    temporal_context: 'ongoing',
    related_findings: ['finding-3'],
    contradicts: [],
    is_promoted: false,
    created_at: '2024-01-20T10:20:00Z',
  },
];

// Mock sources
export const mockSources: ResearchSource[] = [
  {
    id: 'source-1',
    is_global: false,
    url: 'https://example.com/news/company-earnings',
    url_hash: 'hash1',
    title: 'Company Reports Strong Q4 Earnings',
    domain: 'example.com',
    snippet: 'The company exceeded analyst expectations with strong quarterly results...',
    credibility_score: 0.95,
    source_type: 'news',
    discovered_at: '2024-01-18T08:00:00Z',
    citation_count: 5,
  },
  {
    id: 'source-2',
    is_global: false,
    url: 'https://research.org/market-analysis',
    url_hash: 'hash2',
    title: 'Market Analysis: Tech Sector Outlook',
    domain: 'research.org',
    snippet: 'Comprehensive analysis of current market trends and future projections...',
    credibility_score: 0.88,
    source_type: 'academic',
    discovered_at: '2024-01-17T14:30:00Z',
    citation_count: 12,
  },
  {
    id: 'source-3',
    is_global: false,
    url: 'https://industry-insider.com/predictions',
    url_hash: 'hash3',
    title: 'Industry Predictions for 2025',
    domain: 'industry-insider.com',
    snippet: 'Leading analysts share their forecasts for the coming year...',
    credibility_score: 0.72,
    source_type: 'blog',
    discovered_at: '2024-01-19T09:15:00Z',
    citation_count: 3,
  },
  {
    id: 'source-4',
    is_global: false,
    url: 'https://corp.com/press-releases/restructuring',
    url_hash: 'hash4',
    title: 'Official Press Release: Strategic Restructuring',
    domain: 'corp.com',
    snippet: 'The company today announced a comprehensive restructuring plan...',
    credibility_score: 0.90,
    source_type: 'corporate',
    discovered_at: '2024-01-10T16:00:00Z',
    citation_count: 8,
  },
  {
    id: 'source-5',
    is_global: false,
    url: 'https://gov.org/economic-data',
    url_hash: 'hash5',
    title: 'Economic Indicators Report',
    domain: 'gov.org',
    snippet: 'Official government data on economic performance indicators...',
    credibility_score: 0.98,
    source_type: 'government',
    discovered_at: '2024-01-15T11:00:00Z',
    citation_count: 20,
  },
];

// Mock contradictions
export const mockContradictions: ResearchContradiction[] = [
  {
    id: 'contradiction-1',
    session_id: 'session-1',
    finding_id_1: 'finding-1',
    finding_id_2: 'finding-4',
    claim_1: 'Revenue growth was driven by cloud services expansion',
    claim_2: 'Seasonal patterns account for most revenue fluctuations',
    source_1: 'source-1',
    source_2: 'source-2',
    significance: 'Medium - Different explanations for revenue patterns',
    resolution_hint: 'Both factors may contribute, with cloud growth providing baseline and seasonality adding variance',
    created_at: '2024-01-20T12:00:00Z',
  },
  {
    id: 'contradiction-2',
    session_id: 'session-1',
    claim_1: 'Market will reach $50B by 2025',
    claim_2: 'Conservative estimates suggest $35B market size',
    significance: 'High - Significant variance in market projections',
    resolution_hint: 'Different methodologies and assumptions in forecasting',
    created_at: '2024-01-20T12:05:00Z',
  },
];

// Mock gaps
export const mockGaps: ResearchGap[] = [
  {
    id: 'gap-1',
    session_id: 'session-1',
    gap_type: 'temporal',
    description: 'Limited information about company performance between 2020-2022',
    priority: 'high',
    suggested_queries: ['Company performance 2020', 'COVID impact analysis'],
    related_finding_ids: ['finding-1'],
    gap_start: '2020-01-01',
    gap_end: '2022-01-01',
    created_at: '2024-01-20T13:00:00Z',
  },
  {
    id: 'gap-2',
    session_id: 'session-1',
    gap_type: 'actor',
    description: 'Competitor analysis is incomplete - missing data on key rivals',
    priority: 'medium',
    suggested_queries: ['Competitor analysis', 'Market share breakdown'],
    related_finding_ids: ['finding-2'],
    missing_actor: 'TechRival Inc',
    created_at: '2024-01-20T13:05:00Z',
  },
  {
    id: 'gap-3',
    session_id: 'session-1',
    gap_type: 'evidence',
    description: 'Claims about partnership benefits lack independent verification',
    priority: 'low',
    suggested_queries: ['TechCorp partnership results', 'Independent analysis'],
    related_finding_ids: ['finding-5'],
    created_at: '2024-01-20T13:10:00Z',
  },
];

// Mock causal chains
export const mockCausalChains: CausalChain[] = [
  {
    id: 'chain-1',
    session_id: 'session-1',
    finding_ids: ['finding-3', 'finding-5', 'finding-1'],
    descriptions: [
      'CEO announces restructuring initiative',
      'Partnership with TechCorp accelerates development',
      'Company reports 25% revenue increase',
    ],
    created_at: '2024-01-20T14:00:00Z',
  },
  {
    id: 'chain-2',
    session_id: 'session-1',
    finding_ids: ['finding-4', 'finding-2'],
    descriptions: [
      'Historical seasonal patterns identified',
      'Analysts predict continued market growth',
    ],
    created_at: '2024-01-20T14:05:00Z',
  },
];

// Mock entities
export const mockEntities: KnowledgeEntity[] = [
  {
    id: 'entity-1',
    canonical_name: 'John Smith',
    entity_type: 'person',
    aliases: ['J. Smith', 'CEO Smith'],
    name_hash: 'hash1',
    description: 'Chief Executive Officer of the company since 2019',
    profile_data: { role: 'CEO', tenure: '5 years' },
    external_ids: {},
    mention_count: 12,
    claim_count: 5,
    is_verified: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'entity-2',
    canonical_name: 'TechCorp Industries',
    entity_type: 'organization',
    aliases: ['TechCorp', 'TC Industries'],
    name_hash: 'hash2',
    description: 'Strategic partner company specializing in cloud infrastructure',
    profile_data: { industry: 'Technology', founded: '2010' },
    external_ids: {},
    mention_count: 8,
    claim_count: 3,
    is_verified: true,
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-20T11:00:00Z',
  },
  {
    id: 'entity-3',
    canonical_name: 'San Francisco',
    entity_type: 'location',
    aliases: ['SF', 'Bay Area HQ'],
    name_hash: 'hash3',
    description: 'Company headquarters location',
    profile_data: { type: 'city', region: 'California' },
    external_ids: {},
    mention_count: 4,
    claim_count: 1,
    is_verified: true,
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-20T12:00:00Z',
  },
  {
    id: 'entity-4',
    canonical_name: 'Annual Shareholder Meeting 2024',
    entity_type: 'event',
    aliases: ['ASM 2024', 'Shareholder Meeting'],
    name_hash: 'hash4',
    description: 'Annual gathering of company shareholders',
    profile_data: { date: '2024-01-10', location: 'San Francisco' },
    external_ids: {},
    mention_count: 6,
    claim_count: 2,
    is_verified: false,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-20T13:00:00Z',
  },
  {
    id: 'entity-5',
    canonical_name: 'Jane Doe',
    entity_type: 'person',
    aliases: ['J. Doe', 'CFO Doe'],
    name_hash: 'hash5',
    description: 'Chief Financial Officer',
    profile_data: { role: 'CFO', tenure: '3 years' },
    external_ids: {},
    mention_count: 5,
    claim_count: 2,
    is_verified: true,
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-20T14:00:00Z',
  },
];

// Mock perspectives
export const mockPerspectives: ResearchPerspective[] = [
  {
    id: 'perspective-1',
    session_id: 'session-1',
    perspective_type: 'financial',
    analysis_text: 'The financial outlook appears positive with strong revenue growth indicators. The 25% quarterly increase suggests effective market positioning and operational efficiency.',
    key_insights: [
      'Revenue growth exceeds industry average',
      'Cloud services emerging as primary growth driver',
      'Cost optimization initiatives showing results',
    ],
    confidence: 0.85,
    findings_analyzed: ['finding-1', 'finding-4'],
    sources_cited: ['source-1', 'source-2'],
    recommendations: [
      'Continue investment in cloud infrastructure',
      'Monitor seasonal patterns for better forecasting',
    ],
    warnings: [
      'Market volatility may impact projections',
    ],
    created_at: '2024-01-20T15:00:00Z',
  },
  {
    id: 'perspective-2',
    session_id: 'session-1',
    perspective_type: 'technological',
    analysis_text: 'The restructuring initiative combined with strategic partnerships indicates a deliberate pivot toward technology-driven growth.',
    key_insights: [
      'Partnership strategy accelerating innovation',
      'Restructuring aligns with market trends',
      'Leadership demonstrating adaptability',
    ],
    confidence: 0.78,
    findings_analyzed: ['finding-3', 'finding-5'],
    sources_cited: ['source-3', 'source-4'],
    recommendations: [
      'Expand partnership ecosystem',
      'Communicate restructuring benefits to stakeholders',
    ],
    warnings: [
      'Execution risk in transformation programs',
      'Employee morale may be affected by changes',
    ],
    created_at: '2024-01-20T15:30:00Z',
  },
  {
    id: 'perspective-3',
    session_id: 'session-1',
    perspective_type: 'economic',
    analysis_text: 'Competitive positioning appears strong but gaps exist in understanding rival strategies and market share dynamics.',
    key_insights: [
      'First-mover advantage in cloud adoption',
      'Brand recognition remains strong',
    ],
    confidence: 0.65,
    findings_analyzed: ['finding-2'],
    sources_cited: ['source-3'],
    recommendations: [
      'Conduct comprehensive competitor analysis',
      'Monitor emerging market entrants',
    ],
    warnings: [
      'Incomplete competitor intelligence',
      'Market disruption risk from new entrants',
    ],
    created_at: '2024-01-20T16:00:00Z',
  },
];

// Mock stats for OverviewView
export const mockStats = {
  findings: mockFindings.length,
  sources: mockSources.length,
  perspectives: mockPerspectives.length,
  avgConfidence: 0.80,
  highConfidence: 3,
  redFlags: 1,
  gaps: mockGaps.length,
};

// Mock session with all details for OverviewView
export const mockSession: SessionWithDetails = {
  id: 'session-1',
  workspace_id: 'workspace-1',
  title: 'Company Performance Analysis',
  query: 'Analyze company financial performance and strategic initiatives',
  template_type: 'financial',
  status: 'completed',
  topic_ids: [],
  parameters: {},
  claim_count: 15,
  source_count: mockSources.length,
  created_at: '2024-01-20T08:00:00Z',
  updated_at: '2024-01-20T16:00:00Z',
  completed_at: '2024-01-20T16:00:00Z',
  findings: mockFindings,
  sources: mockSources,
  perspectives: mockPerspectives,
  entities: mockEntities,
  relationships: [],
  contradictions: mockContradictions,
  gaps: mockGaps,
  causal_chains: mockCausalChains,
};
