'use client';

import { useState, useCallback, useEffect } from 'react';

const PROJECT_PATH = 'C:\\Users\\mkdol\\dolla\\res';
const PREFERENCES_FILE = '.claude/discovery-preferences.md';

function buildLearnPrompt(unreviewed: UnreviewedTopic[]): string {
  const accepted = unreviewed.filter(t => t.user_verdict === 'accepted');
  const rejected = unreviewed.filter(t => t.user_verdict === 'rejected');
  const topicIds = unreviewed.map(t => t.id);

  const formatTopic = (t: UnreviewedTopic) => {
    const parts = [
      `- **${t.title}**`,
      t.source_slug ? `  Source: ${t.source_slug}` : '',
      t.description ? `  Description: ${t.description}` : '',
      t.claim ? `  Claim: "${t.claim}"` : '',
      t.suggested_template ? `  Template: ${t.suggested_template}` : '',
      t.source_bias ? `  Bias: ${t.source_bias}` : '',
      t.debunkable ? `  Debunkability: ${t.debunkable}/5` : '',
      t.signals?.length ? `  Signals: ${t.signals.join(', ')}` : '',
    ];
    return parts.filter(Boolean).join('\n');
  };

  return `# Preference Learning Task

## Mission

Analyze the user's accepted and rejected topic decisions to learn their preferences. Write a **concise preference summary** that the Discover system can reference to improve future topic selection.

## IMPORTANT RULES

1. **DO NOT override or replace** the base discovery patterns. Your output EXTENDS the existing discovery prompt — it does not replace it.
2. Be **conservative** in your conclusions. Look for clear, repeated patterns, not one-off decisions.
3. Focus on **actionable signals**: what makes a topic interesting vs uninteresting to this user.
4. If the data is too limited (< 5 decisions), note that and provide only tentative observations.

## User Decisions

### Accepted Topics (${accepted.length})
${accepted.length > 0 ? accepted.map(formatTopic).join('\n\n') : '_None_'}

### Rejected Topics (${rejected.length})
${rejected.length > 0 ? rejected.map(formatTopic).join('\n\n') : '_None_'}

## Analysis Instructions

Analyze the decisions above and identify patterns in these dimensions:

1. **Topic Categories**: Which categories/domains does the user prefer? (politics, tech, finance, science, etc.)
2. **Source Preferences**: Any bias toward or against specific news sources?
3. **Template Preferences**: Which research templates (debunk_claim, actor_investigation, etc.) align with accepted topics?
4. **Claim Quality**: Does the user prefer highly debunkable claims (score 4-5) or more complex ones (1-2)?
5. **Signal Preferences**: Does the user favor breaking, trending, or controversial topics?
6. **Bias Patterns**: Does the user prefer topics from sources with a particular political leaning?
7. **Anti-patterns**: What kinds of topics does the user consistently reject?

## Output

After analysis, write the preference summary to a file. Use this exact approach:

\`\`\`bash
cat > ${PREFERENCES_FILE} << 'PREFS_EOF'
# Discovery Preferences (Auto-generated by Learn)
# Last updated: [current date]
# Based on [N] user decisions ([A] accepted, [R] rejected)
#
# IMPORTANT: These preferences EXTEND the base discovery prompt.
# They do not override the core topic extraction rules.

## Preferred Topics
[List patterns the user prefers — be specific and actionable]

## Avoided Topics
[List patterns the user rejects — be specific]

## Quality Signals
[What makes a topic "good" for this user]

## Template Affinity
[Which templates align with user interest]

## Notes
[Any caveats, limited data warnings, or confidence levels]
PREFS_EOF
\`\`\`

After writing the file, mark all reviewed topics by running:

\`\`\`bash
curl -s -X POST http://localhost:3000/api/topics/mark-reviewed \
  -H "Content-Type: application/json" \
  -d '{"topicIds": ${JSON.stringify(topicIds)}}'
\`\`\`

## Execution Steps

1. **Analyze**: Read through all accepted and rejected topics
2. **Identify patterns**: Look for repeated themes across decisions
3. **Write preferences**: Save to \`${PREFERENCES_FILE}\` with clear, actionable patterns
4. **Mark reviewed**: POST to mark-reviewed endpoint so these aren't re-analyzed
5. **Report**: Summarize what you learned

Begin analysis now.`;
}

interface UnreviewedTopic {
  id: string;
  title: string;
  description: string | null;
  user_verdict: 'accepted' | 'rejected';
  source_slug: string;
  signals: string[] | null;
  claim: string | null;
  source_bias: string | null;
  debunkable: number | null;
  suggested_template: string | null;
}

export function useLearn() {
  const [isTerminalOpen, setIsTerminalOpen] = useState(false);
  const [isLearning, setIsLearning] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [unreviewedCount, setUnreviewedCount] = useState(0);

  // Fetch unreviewed count on mount and periodically
  const fetchUnreviewedCount = useCallback(async () => {
    try {
      const res = await fetch('/api/topics/unreviewed-count');
      if (res.ok) {
        const data = await res.json();
        setUnreviewedCount(data.count ?? 0);
      }
    } catch {
      // Silently fail - count is non-critical
    }
  }, []);

  useEffect(() => {
    fetchUnreviewedCount();
    const interval = setInterval(fetchUnreviewedCount, 60000); // every 60s
    return () => clearInterval(interval);
  }, [fetchUnreviewedCount]);

  const startLearning = useCallback(async () => {
    try {
      // Fetch full unreviewed topics for the prompt
      const res = await fetch('/api/topics/unreviewed');
      if (!res.ok) {
        console.error('[Learn] Failed to fetch unreviewed topics');
        return;
      }

      const data = await res.json();
      if (!data.topics?.length) {
        console.warn('[Learn] No unreviewed topics to analyze');
        return;
      }

      const p = buildLearnPrompt(data.topics);
      setPrompt(p);
      setIsLearning(true);
      setIsTerminalOpen(true);
    } catch (error) {
      console.error('[Learn] Error starting:', error);
    }
  }, []);

  const closeTerminal = useCallback(() => {
    setIsTerminalOpen(false);
    setIsLearning(false);
  }, []);

  const handleComplete = useCallback(() => {
    setIsLearning(false);
    // Refresh count after learning completes
    fetchUnreviewedCount();
  }, [fetchUnreviewedCount]);

  const handleError = useCallback((error: string) => {
    console.error('[Learn] Error:', error);
    setIsLearning(false);
  }, []);

  return {
    isTerminalOpen,
    isLearning,
    prompt,
    projectPath: PROJECT_PATH,
    unreviewedCount,
    startLearning,
    closeTerminal,
    handleComplete,
    handleError,
    refreshCount: fetchUnreviewedCount,
  };
}
